# Generated by Django 6.0.2 on 2026-03-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_variants",
            name="sales_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Продажи"),
        ),
        migrations.AddField(
            model_name="product_variants",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
        ),
        migrations.AddField(
            model_name="userprofiles",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Возраст"
            ),
        ),
        migrations.AddField(
            model_name="userprofiles",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Мужской"), ("female", "Женский")],
                max_length=20,
                null=True,
                verbose_name="Пол",
            ),
        ),
    ]
