# Generated by Django 6.0.2 on 2026-03-10 16:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product_images",
            new_name="Product_image",
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Общая сумма",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price_per_unit",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Цена за штуку",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Итоговая цена",
            ),
        ),
        migrations.CreateModel(
            name="Product_variant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=19,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, verbose_name="Версия изменений"),
                ),
                (
                    "sku",
                    models.TextField(blank=True, unique=True, verbose_name="Артикул"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант продукта",
                "verbose_name_plural": "Варианты продуктов",
            },
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.product_variant"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.product_variant",
                verbose_name="Вариант товара",
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=19,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Сумма транзакции",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="ID транзакции"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(max_length=50, verbose_name="Метод оплаты"),
                ),
                (
                    "status",
                    models.CharField(max_length=20, verbose_name="Статус транзакции"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="main.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название склада"),
                ),
                ("address", models.TextField(verbose_name="Адрес склада")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouses",
                        to="main.storeprofile",
                        verbose_name="Продавец (Магазин)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "reserved_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Зарезервированное количество"
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="main.product_variant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="main.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Остаток на складе",
                "verbose_name_plural": "Остатки на складах",
                "unique_together": {("product_variant", "warehouse")},
            },
        ),
        migrations.DeleteModel(
            name="Product_variants",
        ),
    ]
