# Generated by Django 6.0.2 on 2026-03-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_product_images_product_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Адрес", "verbose_name_plural": "Адреса"},
        ),
    ]
