# Generated by Django 6.0.2 on 2026-03-19 07:21

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_product_variants_sales_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categories",
            name="path",
        ),
        migrations.RemoveField(
            model_name="product_variants",
            name="sales_count",
        ),
        migrations.RemoveField(
            model_name="product_variants",
            name="views_count",
        ),
        migrations.AddField(
            model_name="categories",
            name="level",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="categories",
            name="lft",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="categories",
            name="rght",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="categories",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="products",
            name="sales_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Продажи"),
        ),
        migrations.AddField(
            model_name="products",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
        ),
        migrations.AlterField(
            model_name="categories",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="main.categories",
            ),
        ),
        migrations.CreateModel(
            name="ProductAttributeValues",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=255, verbose_name="Значение")),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.categoryattributes",
                        verbose_name="Атрибут категории",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="main.products",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение атрибута",
                "verbose_name_plural": "Значения атрибутов",
                "unique_together": {("product", "attribute")},
            },
        ),
    ]
