# Generated by Django 6.0.2 on 2026-03-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_address_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает обработки"),
                    ("completed", "Завершена"),
                    ("failed", "Неудачная"),
                    ("refunded", "Возвращена"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус транзакции",
            ),
        ),
    ]
