# Generated by Django 6.0.2 on 2026-03-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Заполняется автоматически!",
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="product_variant",
            name="sku",
            field=models.CharField(blank=True, unique=True, verbose_name="Артикул"),
        ),
    ]
