# Generated by Django 6.0.2 on 2026-03-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_products_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeprofiles',
            old_name='address',
            new_name='legal_address',
        ),
        migrations.RemoveField(
            model_name='storeprofiles',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='storeprofiles',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='storeprofiles',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Не подтвержден'), ('pending', 'На проверке'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен')], default='unverified', max_length=20, verbose_name='Статус верификации'),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='storeprofiles',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании'),
        ),
    ]
