# Generated by Django 6.0.2 on 2026-03-18 16:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0005_alter_product_slug_alter_product_variant_sku"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Address",
            new_name="Addresses",
        ),
        migrations.RenameModel(
            old_name="Brand",
            new_name="Brands",
        ),
        migrations.RenameModel(
            old_name="Cart",
            new_name="Carts",
        ),
        migrations.RenameModel(
            old_name="Category",
            new_name="Categories",
        ),
        migrations.RenameModel(
            old_name="CategoryAttribute",
            new_name="CategoryAttributes",
        ),
        migrations.RenameModel(
            old_name="Order",
            new_name="Orders",
        ),
        migrations.RenameModel(
            old_name="Product_image",
            new_name="Product_images",
        ),
        migrations.RenameModel(
            old_name="StoreProfile",
            new_name="StoreProfiles",
        ),
        migrations.RenameModel(
            old_name="Transaction",
            new_name="Transactions",
        ),
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="UserProfiles",
        ),
        migrations.RenameModel(
            old_name="Warehouse",
            new_name="Warehouses",
        ),
        migrations.RenameModel(
            old_name="User",
            new_name="Users",
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("content", models.TextField(verbose_name="Содержание сообщения")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.RenameModel(
            old_name="CartItem",
            new_name="CartItems",
        ),
        migrations.RenameModel(
            old_name="OrderItem",
            new_name="OrderItems",
        ),
        migrations.RenameModel(
            old_name="Product",
            new_name="Products",
        ),
        migrations.RenameModel(
            old_name="Stock",
            new_name="Stocks",
        ),
        migrations.CreateModel(
            name="Product_variants",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=19,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, verbose_name="Версия изменений"),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Уникальный идентификатор варианта товара. Заполняется автоматически при сохранении.",
                        unique=True,
                        verbose_name="Артикул",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.products",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант продукта",
                "verbose_name_plural": "Варианты продуктов",
            },
        ),
        migrations.AlterField(
            model_name="cartitems",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.product_variants"
            ),
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="product_variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.product_variants",
                verbose_name="Вариант товара",
            ),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock",
                to="main.product_variants",
            ),
        ),
        migrations.DeleteModel(
            name="Product_variant",
        ),
    ]
