# Generated by Django 6.0.2 on 2026-04-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_favorites"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofiles",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Отчество"
            ),
        ),
    ]
