# Generated by Django 6.0.2 on 2026-05-01 17:17

import django.db.models.deletion
import main.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_userprofiles_patronymic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brands",
            name="logo_image",
            field=models.ImageField(
                upload_to="brands/",
                validators=[main.validators.validate_image_size],
                verbose_name="Лого",
            ),
        ),
        migrations.AlterField(
            model_name="product_images",
            name="image",
            field=models.ImageField(
                upload_to="products/", validators=[main.validators.validate_image_size]
            ),
        ),
        migrations.AlterField(
            model_name="storeprofiles",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="store_logos/",
                validators=[main.validators.validate_image_size],
                verbose_name="Логотип",
            ),
        ),
        migrations.AlterField(
            model_name="userprofiles",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[main.validators.validate_image_size],
                verbose_name="Аватар",
            ),
        ),
        migrations.CreateModel(
            name="Friends",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friends_with",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Друг",
                "verbose_name_plural": "Друзья",
                "db_table": "friends",
                "unique_together": {("user", "friend")},
            },
        ),
    ]
