# Generated by Django 6.0.2 on 2026-05-03 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_brands_logo_image_alter_product_images_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplies",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    models.PositiveIntegerField(verbose_name="Количество поставки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата поставки"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Примечание"),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.product_variants",
                        verbose_name="Вариант товара",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Продавец",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.warehouses",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставка",
                "verbose_name_plural": "Поставки",
            },
        ),
    ]
